- name: Copy ssh key to /tmp
  copy:
    src:  Hiveschool.pem
    dest: /tmp/hiveschool.pem
    mode: 0400

- name: Create teacher instance
  ec2:
    image:            ami-accff2b1
    instance_type:    t2.micro
    region:           eu-central-1
    aws_access_key:   "{{ aws.credentials.access_key }}"
    aws_secret_key:   "{{ aws.credentials.secret_key }}"
    wait:             yes
    group_id:         sg-9fd150f6
    key_name:         Hiveschool
    count_tag:
      role: teacher
    exact_count:      1
  register: teacher
- name: Tag teacher instance
  ec2_tag:
  args:
    aws_access_key:   "{{ aws.credentials.access_key }}"
    aws_secret_key:   "{{ aws.credentials.secret_key }}"
    resource: "{{ item.id }}"
    region:   eu-central-1
    tags:
      role: teacher
  with_items: teacher.instances
- name: Register teacher instance
  add_host:
    hostname:                     "{{ item.public_ip }}"
    groupname:                    teacher
    ansible_ssh_private_key_file: /tmp/hiveschool.pem
    ansible_ssh_user:             ubuntu
  with_items: teacher.tagged_instances
- name: Wait for teacher instance ssh to come up
  wait_for:
    host:     "{{ item.public_ip }}"
    port:     22
    delay:    60
    timeout:  300
    state:    started
  with_items: teacher.instances

- name: Create student instances
  ec2:
    image:            ami-accff2b1
    instance_type:    t2.micro
    region:           eu-central-1
    aws_access_key:   "{{ aws.credentials.access_key }}"
    aws_secret_key:   "{{ aws.credentials.secret_key }}"
    wait:             yes
    group_id:         sg-9fd150f6
    key_name:         Hiveschool
    count_tag:
      role: student
    instance_tags:
      role: student
    exact_count:      "{{ students_count }}"
  register: students
- name: Tag students instance
  ec2_tag:
  args:
    aws_access_key:   "{{ aws.credentials.access_key }}"
    aws_secret_key:   "{{ aws.credentials.secret_key }}"
    resource: "{{ item.id }}"
    region:   eu-central-1
    tags:
      role: student
  with_items: students.instances
- name: Register student instances
  add_host:
    hostname:   "{{ item.public_ip }}"
    groupname:  students
    ansible_ssh_private_key_file: /tmp/hiveschool.pem
    ansible_ssh_user:             ubuntu
  with_items: students.tagged_instances
- name: Wait for student instances ssh to come up
  wait_for:
    host:   "{{ item.public_ip }}"
    port:   22
    delay:    60
    timeout:  300
    state:  started
  with_items: students.instances

  # with_sequence: start=1 end={{ students_count }} format=student%02i
